//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Difdisofil.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Орієнтація спліт-контейнера вкладки Піксель
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Орієнтація спліт-контейнера вкладки Піксель")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vertical")]
        public global::System.Windows.Forms.Orientation sCPo {
            get {
                return ((global::System.Windows.Forms.Orientation)(this["sCPo"]));
            }
            set {
                this["sCPo"] = value;
            }
        }
        
        /// <summary>
        /// Відстань спілт-контейнера вкладки Піксель
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Відстань спілт-контейнера вкладки Піксель")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("650")]
        public int sCPsd {
            get {
                return ((int)(this["sCPsd"]));
            }
            set {
                this["sCPsd"] = value;
            }
        }
        
        /// <summary>
        /// Розташування форми
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Розташування форми")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("150, 150")]
        public global::System.Drawing.Point FMl {
            get {
                return ((global::System.Drawing.Point)(this["FMl"]));
            }
            set {
                this["FMl"] = value;
            }
        }
        
        /// <summary>
        /// Розмір форми
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Розмір форми")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("923, 629")]
        public global::System.Drawing.Size FMs {
            get {
                return ((global::System.Drawing.Size)(this["FMs"]));
            }
            set {
                this["FMs"] = value;
            }
        }
        
        /// <summary>
        /// Відстань спілт-контейнера вкладки Лінія
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Відстань спілт-контейнера вкладки Лінія")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("371")]
        public int sCLsd {
            get {
                return ((int)(this["sCLsd"]));
            }
            set {
                this["sCLsd"] = value;
            }
        }
        
        /// <summary>
        /// Орієнтація спліт-контейнера вкладки Лінія
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Орієнтація спліт-контейнера вкладки Лінія")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Horizontal")]
        public global::System.Windows.Forms.Orientation sCLo {
            get {
                return ((global::System.Windows.Forms.Orientation)(this["sCLo"]));
            }
            set {
                this["sCLo"] = value;
            }
        }
        
        /// <summary>
        /// Відстань спілт-контейнера вкладки Графік і таблиця
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Відстань спілт-контейнера вкладки Графік і таблиця")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("694")]
        public int sCGsd {
            get {
                return ((int)(this["sCGsd"]));
            }
            set {
                this["sCGsd"] = value;
            }
        }
        
        /// <summary>
        /// Орієнтація спліт-контейнера вкладки Графік і таблиця
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Орієнтація спліт-контейнера вкладки Графік і таблиця")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vertical")]
        public global::System.Windows.Forms.Orientation sCGo {
            get {
                return ((global::System.Windows.Forms.Orientation)(this["sCGo"]));
            }
            set {
                this["sCGo"] = value;
            }
        }
    }
}
